# config/promtail/config.yml in your Rails app
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://conductor.campoli.me:3100/loki/api/v1/push

scrape_configs:
  - job_name: rails_app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: rails
          app: shortener
          environment: production
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: message
            method: method
            path: path
            status: status
            duration: duration
            user_id: user_id
            request_id: request_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          method:
          status: