default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "pguser" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: shortener_development

test:
  <<: *default
  database: shortener_test

production:
  primary: &primary_production
    <<: *default
    database: shortener_production