service: shortener

image: xkraty/shortener

servers:
  web:
    - s.campoli.me

proxy:
  ssl: true
  host: s.campoli.me

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    APP_HOST: s.campoli.me
    # OTEL configuration for your Rails app - correct container hostname
    OTEL_EXPORTER_OTLP_ENDPOINT: http://shortener-otel-collector:4318
    OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://shortener-otel-collector:4318
    OTEL_TRACES_EXPORTER: 'otlp'
    OTEL_LOG_LEVEL: 'debug'
    OTEL_SERVICE_NAME: TheShortener
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PORT
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    # SignOz Cloud credentials (use ingestion key, not access token)
    - SIGNOZ_INGESTION_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

accessories:
  db:
    image: postgres:17.2-alpine
    host: s.campoli.me
    port: "127.0.0.1:5433:5432"
    directories:
      - data:/var/lib/postgresql/data
    env:
      secret:
        - POSTGRES_PORT
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_HOST