service: shortener

image: xkraty/shortener

servers:
  web:
    - s.campoli.me

proxy:
  ssl: true
  host: s.campoli.me

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    APP_HOST: s.campoli.me
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

# Use a persistent storage volume so the SQLite database survives deploys.
volumes:
  - "shortener_storage:/rails/storage"