# config/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Collect system metrics from the server
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: {}
      disk: {}
      load: {}
      filesystem: {}
      memory: {}
      network: {}
      paging: {}
      # Removed process scraper to avoid /etc/passwd errors in container
  
  filelog:
    include: [/var/lib/docker/containers/*/*-json.log]
    poll_interval: 200ms
    start_at: end
    include_file_name: false
    include_file_path: false
    operators:
      - id: container-parser
        type: container
        format: docker

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

  # Adds resource attributes like hostname, OS info
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    system:
      hostname_sources: [os]

extensions:
  health_check: {}
  zpages: {}

exporters:
  otlp:
    # IMPORTANT: Replace with your actual region (us, eu, or in)
    # For US: ingest.us.signoz.cloud:443
    # For EU: ingest.eu.signoz.cloud:443  
    # For India: ingest.in.signoz.cloud:443
    endpoint: "ingest.us.signoz.cloud:443"  # Change 'us' to your region
    tls:
      insecure: false
    headers:
      "signoz-ingestion-key": "${SIGNOZ_INGESTION_KEY}"

  # Useful for debugging
  debug:
    verbosity: normal

service:
  telemetry:
    metrics:
      level: basic
  
  extensions: [health_check, zpages]
  
  pipelines:
    # Application traces from your Rails app
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    # Application metrics from your Rails app
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    # System/host metrics from the server
    metrics/internal:
      receivers: [hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [otlp]

    # Application logs from your Rails app
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [otlp]